import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { fetchSeedBindings } from "./wikidata-seed";

const outputPath = resolve("db/seed.sql");
const bindings = await fetchSeedBindings();
if (bindings.length < 500) {
  throw new Error(
    `Expected at least 500 seed people, received ${bindings.length}`,
  );
}

const now = new Date().toISOString();
const statements = [
  "-- Generated by scripts/generate-seed.ts",
  `-- Generated at ${now}`,
  "BEGIN TRANSACTION;",
];

for (const binding of bindings) {
  const qid = binding.person.value.split("/").pop();
  if (!qid) continue;

  const canonicalName = binding.personLabel.value;
  const description = binding.personDescription?.value ?? null;
  const articleUrl = binding.article.value;
  const articleTitle = decodeURIComponent(articleUrl.split("/wiki/").pop() ?? "")
    .replace(/_/gu, " ");

  statements.push(
    `INSERT INTO persons (
      qid, canonical_name, normalized_name, description, wikipedia_title,
      wikipedia_url, primary_language, is_human, qualifies_as_woman,
      has_wikipedia_sitelink, is_fictional, validation_status,
      validation_source, first_verified_at, last_verified_at, created_at, updated_at
    ) VALUES (
      ${sql(qid)}, ${sql(canonicalName)}, ${sql(normalize(canonicalName))},
      ${sql(description)}, ${sql(articleTitle)}, ${sql(articleUrl)}, 'en',
      1, 1, 1, 0, 'verified', 'seed', ${sql(now)}, ${sql(now)}, ${sql(now)}, ${sql(now)}
    )
    ON CONFLICT(qid) DO UPDATE SET
      canonical_name = excluded.canonical_name,
      normalized_name = excluded.normalized_name,
      description = excluded.description,
      wikipedia_title = excluded.wikipedia_title,
      wikipedia_url = excluded.wikipedia_url,
      is_human = 1,
      qualifies_as_woman = 1,
      has_wikipedia_sitelink = 1,
      is_fictional = 0,
      validation_status = 'verified',
      validation_source = 'seed',
      last_verified_at = excluded.last_verified_at,
      updated_at = excluded.updated_at;`,
  );

  for (const [alias, aliasType] of uniqueAliases([
    [canonicalName, "canonical"],
    [articleTitle, "redirect"],
  ])) {
    statements.push(
      `INSERT OR IGNORE INTO person_aliases (
        person_qid, alias, normalized_alias, alias_type, language_code,
        source, created_at, updated_at
      ) VALUES (
        ${sql(qid)}, ${sql(alias)}, ${sql(normalize(alias))}, ${sql(aliasType)},
        'en', 'seed', ${sql(now)}, ${sql(now)}
      );`,
    );
  }
}

statements.push("COMMIT;", "");
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, statements.join("\n"), "utf8");
console.log(
  `Generated ${outputPath} with ${bindings.length} people.`,
);

function normalize(value: string): string {
  return value.normalize("NFKC").trim().replace(/\s+/gu, " ").toLowerCase();
}

function sql(value: string | null): string {
  return value === null ? "NULL" : `'${value.replace(/'/gu, "''")}'`;
}

function uniqueAliases(
  values: Array<[string, string]>,
): Array<[string, string]> {
  const seen = new Set<string>();
  return values.filter(([value]) => {
    const key = normalize(value);
    if (!key || seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
